#!/usr/bin/env python3
"""Generates the Android evdev -> HID table from core/keymap/src/lib.rs.

Run from the repository root:  python3 tools/gen_android_keymap.py
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "core/keymap/src/lib.rs"
OUTS = {
    "com.keymahub.hid": ROOT / "android/keymahub/src/main/java/com/keymahub/hid/EvdevKeymap.kt",
}

CONSTS = {"HID_LANG1_HANGUL": 0x90, "HID_LANG2_HANJA": 0x91}
ENTRY = re.compile(r'k\(\s*(0x[0-9A-Fa-f]+|HID_\w+)\s*,\s*(\d+)\s*,\s*[^,]+,\s*"([^"]+)"\s*\)')


def main() -> None:
    rows = []
    for hid, evdev, name in ENTRY.findall(SRC.read_text()):
        rows.append((int(evdev), CONSTS[hid] if hid in CONSTS else int(hid, 16), name))
    rows.sort()
    body = "\n".join(f"        put({e}, 0x{h:02X}) // {n}" for e, h, n in rows)
    for package, out in OUTS.items():
        out.write_text(f"""package {package}

// GENERATED by tools/gen_android_keymap.py from core/keymap/src/lib.rs — do not edit.

/** Linux evdev `KEY_*` code → USB HID keyboard usage. */
object EvdevKeymap {{
    private val table: Map<Int, Int> = buildMap {{
{body}
    }}

    fun toHid(evdev: Int): Int? = table[evdev]

    const val SIZE = {len(rows)}
}}
""")
        print(f"wrote {len(rows)} entries to {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
